import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 sm:p-10 bg-white shadow-lg rounded-lg">
      <h1 className="text-3xl font-bold text-center mb-6 text-gray-800">Terms & Conditions</h1>
      
      <ol className="list-decimal pl-5 space-y-4 text-gray-700">
        <li>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </li>
        <li>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name 
          <a 
            href="https://astrologerabhishekdubey.in/" 
            className="text-blue-600 hover:underline" 
            target="_blank" 
            rel="noopener noreferrer">
            https://astrologerabhishekdubey.in/
          </a> 
          ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
        </li>
        <li>
          The Platform is owned by <strong className="font-bold">Abhisek Dubey</strong>, a company incorporated under the Companies Act, 1956, with its registered office at NO 15, 107, JAYANAGAR WEST, 4th Cross, 7th Block, Bengaluru, Bengaluru Urban, Karnataka, 560070, Bangalore, India (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
        </li>
        <li>
          Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, you agree to these terms and conditions, constituting your binding obligations with the Platform Owner.
        </li>
        <li>
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </li>
        <li>
          The use of Platform and/or availing of our Services is subject to the following Terms of Use:
          <ol className="list-decimal pl-5 mt-3 space-y-2">
            <li>You agree to provide accurate and complete information during registration and ensure the security of your account.</li>
            <li>We do not guarantee the accuracy, completeness, or suitability of the information provided on the Platform.</li>
            <li>Your use of the Services and the Platform is entirely at your own risk.</li>
            <li>The contents of the Platform are proprietary to us, and you will not claim intellectual property rights over them.</li>
            <li>Unauthorized use of the Platform may result in legal action against you.</li>
            <li>You agree to pay all applicable charges for availing the Services.</li>
            <li>Links to third-party websites are provided for your convenience; accessing them is at your own discretion.</li>
            <li>You acknowledge that initiating a transaction on the Platform constitutes a legally binding contract.</li>
            <li>You agree to indemnify us for any claims arising from your breach of the Terms of Use.</li>
            <li>In case of force majeure, parties will not be liable for non-performance of obligations.</li>
            <li>These Terms are governed by the laws of India, and disputes will be subject to the courts of Bangalore.</li>
          </ol>
        </li>
      </ol>
    </div>
  );
};

export default TermsAndConditions;
